/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AppRouteImport } from './routes/app'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as DashboardTourRouteImport } from './routes/dashboard-tour'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as StackRouteImport } from './routes/stack'
import { Route as UseCasesRouteImport } from './routes/use-cases'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAnalyticsRouteImport } from './routes/app/analytics'
import { Route as AppApiKeysRouteImport } from './routes/app/api-keys'
import { Route as AppInboundRouteImport } from './routes/app/inbound'
import { Route as AppLogsRouteImport } from './routes/app/logs'
import { Route as AppPlacementRouteImport } from './routes/app/placement'
import { Route as AppPreferencesRouteImport } from './routes/app/preferences'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppSuppressionsRouteImport } from './routes/app/suppressions'
import { Route as AppTeamRouteImport } from './routes/app/team'
import { Route as LegalDpaRouteImport } from './routes/legal/dpa'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as AppAudiencesIndexRouteImport } from './routes/app/audiences.index'
import { Route as AppAudiencesAudienceIdRouteImport } from './routes/app/audiences.$audienceId'
import { Route as AppAutomationsIndexRouteImport } from './routes/app/automations.index'
import { Route as AppAutomationsAutomationIdRouteImport } from './routes/app/automations.$automationId'
import { Route as AppBroadcastsIndexRouteImport } from './routes/app/broadcasts.index'
import { Route as AppBroadcastsBroadcastIdRouteImport } from './routes/app/broadcasts.$broadcastId'
import { Route as AppBroadcastsNewRouteImport } from './routes/app/broadcasts.new'
import { Route as AppDomainsIndexRouteImport } from './routes/app/domains.index'
import { Route as AppDomainsDomainIdRouteImport } from './routes/app/domains.$domainId'
import { Route as AppEmailsEmailIdRouteImport } from './routes/app/emails.$emailId'
import { Route as AppSegmentsIndexRouteImport } from './routes/app/segments.index'
import { Route as AppSegmentsSegmentIdRouteImport } from './routes/app/segments.$segmentId'
import { Route as AppTemplatesIndexRouteImport } from './routes/app/templates.index'
import { Route as AppTemplatesTemplateIdRouteImport } from './routes/app/templates.$templateId'
import { Route as AppWebhooksIndexRouteImport } from './routes/app/webhooks.index'
import { Route as AppWebhooksWebhookIdRouteImport } from './routes/app/webhooks.$webhookId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTourRoute = DashboardTourRouteImport.update({
  id: '/dashboard-tour',
  path: '/dashboard-tour',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const StackRoute = StackRouteImport.update({
  id: '/stack',
  path: '/stack',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesRoute = UseCasesRouteImport.update({
  id: '/use-cases',
  path: '/use-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppApiKeysRoute = AppApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AppRoute,
} as any)
const AppInboundRoute = AppInboundRouteImport.update({
  id: '/inbound',
  path: '/inbound',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsRoute = AppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppRoute,
} as any)
const AppPlacementRoute = AppPlacementRouteImport.update({
  id: '/placement',
  path: '/placement',
  getParentRoute: () => AppRoute,
} as any)
const AppPreferencesRoute = AppPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppressionsRoute = AppSuppressionsRouteImport.update({
  id: '/suppressions',
  path: '/suppressions',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const LegalDpaRoute = LegalDpaRouteImport.update({
  id: '/legal/dpa',
  path: '/legal/dpa',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAudiencesIndexRoute = AppAudiencesIndexRouteImport.update({
  id: '/audiences/',
  path: '/audiences/',
  getParentRoute: () => AppRoute,
} as any)
const AppAudiencesAudienceIdRoute = AppAudiencesAudienceIdRouteImport.update({
  id: '/audiences/$audienceId',
  path: '/audiences/$audienceId',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationsIndexRoute = AppAutomationsIndexRouteImport.update({
  id: '/automations/',
  path: '/automations/',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationsAutomationIdRoute =
  AppAutomationsAutomationIdRouteImport.update({
    id: '/automations/$automationId',
    path: '/automations/$automationId',
    getParentRoute: () => AppRoute,
  } as any)
const AppBroadcastsIndexRoute = AppBroadcastsIndexRouteImport.update({
  id: '/broadcasts/',
  path: '/broadcasts/',
  getParentRoute: () => AppRoute,
} as any)
const AppBroadcastsBroadcastIdRoute =
  AppBroadcastsBroadcastIdRouteImport.update({
    id: '/broadcasts/$broadcastId',
    path: '/broadcasts/$broadcastId',
    getParentRoute: () => AppRoute,
  } as any)
const AppBroadcastsNewRoute = AppBroadcastsNewRouteImport.update({
  id: '/broadcasts/new',
  path: '/broadcasts/new',
  getParentRoute: () => AppRoute,
} as any)
const AppDomainsIndexRoute = AppDomainsIndexRouteImport.update({
  id: '/domains/',
  path: '/domains/',
  getParentRoute: () => AppRoute,
} as any)
const AppDomainsDomainIdRoute = AppDomainsDomainIdRouteImport.update({
  id: '/domains/$domainId',
  path: '/domains/$domainId',
  getParentRoute: () => AppRoute,
} as any)
const AppEmailsEmailIdRoute = AppEmailsEmailIdRouteImport.update({
  id: '/emails/$emailId',
  path: '/emails/$emailId',
  getParentRoute: () => AppRoute,
} as any)
const AppSegmentsIndexRoute = AppSegmentsIndexRouteImport.update({
  id: '/segments/',
  path: '/segments/',
  getParentRoute: () => AppRoute,
} as any)
const AppSegmentsSegmentIdRoute = AppSegmentsSegmentIdRouteImport.update({
  id: '/segments/$segmentId',
  path: '/segments/$segmentId',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesIndexRoute = AppTemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesTemplateIdRoute = AppTemplatesTemplateIdRouteImport.update({
  id: '/templates/$templateId',
  path: '/templates/$templateId',
  getParentRoute: () => AppRoute,
} as any)
const AppWebhooksIndexRoute = AppWebhooksIndexRouteImport.update({
  id: '/webhooks/',
  path: '/webhooks/',
  getParentRoute: () => AppRoute,
} as any)
const AppWebhooksWebhookIdRoute = AppWebhooksWebhookIdRouteImport.update({
  id: '/webhooks/$webhookId',
  path: '/webhooks/$webhookId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/app': typeof AppRouteWithChildren
  '/compare': typeof CompareRoute
  '/dashboard-tour': typeof DashboardTourRoute
  '/docs': typeof DocsRoute
  '/pricing': typeof PricingRoute
  '/resources': typeof ResourcesRoute
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/stack': typeof StackRoute
  '/use-cases': typeof UseCasesRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/api-keys': typeof AppApiKeysRoute
  '/app/inbound': typeof AppInboundRoute
  '/app/logs': typeof AppLogsRoute
  '/app/placement': typeof AppPlacementRoute
  '/app/preferences': typeof AppPreferencesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/suppressions': typeof AppSuppressionsRoute
  '/app/team': typeof AppTeamRoute
  '/legal/dpa': typeof LegalDpaRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/app/': typeof AppIndexRoute
  '/app/audiences/$audienceId': typeof AppAudiencesAudienceIdRoute
  '/app/automations/$automationId': typeof AppAutomationsAutomationIdRoute
  '/app/broadcasts/$broadcastId': typeof AppBroadcastsBroadcastIdRoute
  '/app/broadcasts/new': typeof AppBroadcastsNewRoute
  '/app/domains/$domainId': typeof AppDomainsDomainIdRoute
  '/app/emails/$emailId': typeof AppEmailsEmailIdRoute
  '/app/segments/$segmentId': typeof AppSegmentsSegmentIdRoute
  '/app/templates/$templateId': typeof AppTemplatesTemplateIdRoute
  '/app/webhooks/$webhookId': typeof AppWebhooksWebhookIdRoute
  '/app/audiences/': typeof AppAudiencesIndexRoute
  '/app/automations/': typeof AppAutomationsIndexRoute
  '/app/broadcasts/': typeof AppBroadcastsIndexRoute
  '/app/domains/': typeof AppDomainsIndexRoute
  '/app/segments/': typeof AppSegmentsIndexRoute
  '/app/templates/': typeof AppTemplatesIndexRoute
  '/app/webhooks/': typeof AppWebhooksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/compare': typeof CompareRoute
  '/dashboard-tour': typeof DashboardTourRoute
  '/docs': typeof DocsRoute
  '/pricing': typeof PricingRoute
  '/resources': typeof ResourcesRoute
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/stack': typeof StackRoute
  '/use-cases': typeof UseCasesRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/api-keys': typeof AppApiKeysRoute
  '/app/inbound': typeof AppInboundRoute
  '/app/logs': typeof AppLogsRoute
  '/app/placement': typeof AppPlacementRoute
  '/app/preferences': typeof AppPreferencesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/suppressions': typeof AppSuppressionsRoute
  '/app/team': typeof AppTeamRoute
  '/legal/dpa': typeof LegalDpaRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/app': typeof AppIndexRoute
  '/app/audiences/$audienceId': typeof AppAudiencesAudienceIdRoute
  '/app/automations/$automationId': typeof AppAutomationsAutomationIdRoute
  '/app/broadcasts/$broadcastId': typeof AppBroadcastsBroadcastIdRoute
  '/app/broadcasts/new': typeof AppBroadcastsNewRoute
  '/app/domains/$domainId': typeof AppDomainsDomainIdRoute
  '/app/emails/$emailId': typeof AppEmailsEmailIdRoute
  '/app/segments/$segmentId': typeof AppSegmentsSegmentIdRoute
  '/app/templates/$templateId': typeof AppTemplatesTemplateIdRoute
  '/app/webhooks/$webhookId': typeof AppWebhooksWebhookIdRoute
  '/app/audiences': typeof AppAudiencesIndexRoute
  '/app/automations': typeof AppAutomationsIndexRoute
  '/app/broadcasts': typeof AppBroadcastsIndexRoute
  '/app/domains': typeof AppDomainsIndexRoute
  '/app/segments': typeof AppSegmentsIndexRoute
  '/app/templates': typeof AppTemplatesIndexRoute
  '/app/webhooks': typeof AppWebhooksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/app': typeof AppRouteWithChildren
  '/compare': typeof CompareRoute
  '/dashboard-tour': typeof DashboardTourRoute
  '/docs': typeof DocsRoute
  '/pricing': typeof PricingRoute
  '/resources': typeof ResourcesRoute
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/stack': typeof StackRoute
  '/use-cases': typeof UseCasesRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/api-keys': typeof AppApiKeysRoute
  '/app/inbound': typeof AppInboundRoute
  '/app/logs': typeof AppLogsRoute
  '/app/placement': typeof AppPlacementRoute
  '/app/preferences': typeof AppPreferencesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/suppressions': typeof AppSuppressionsRoute
  '/app/team': typeof AppTeamRoute
  '/legal/dpa': typeof LegalDpaRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/app/': typeof AppIndexRoute
  '/app/audiences/$audienceId': typeof AppAudiencesAudienceIdRoute
  '/app/automations/$automationId': typeof AppAutomationsAutomationIdRoute
  '/app/broadcasts/$broadcastId': typeof AppBroadcastsBroadcastIdRoute
  '/app/broadcasts/new': typeof AppBroadcastsNewRoute
  '/app/domains/$domainId': typeof AppDomainsDomainIdRoute
  '/app/emails/$emailId': typeof AppEmailsEmailIdRoute
  '/app/segments/$segmentId': typeof AppSegmentsSegmentIdRoute
  '/app/templates/$templateId': typeof AppTemplatesTemplateIdRoute
  '/app/webhooks/$webhookId': typeof AppWebhooksWebhookIdRoute
  '/app/audiences/': typeof AppAudiencesIndexRoute
  '/app/automations/': typeof AppAutomationsIndexRoute
  '/app/broadcasts/': typeof AppBroadcastsIndexRoute
  '/app/domains/': typeof AppDomainsIndexRoute
  '/app/segments/': typeof AppSegmentsIndexRoute
  '/app/templates/': typeof AppTemplatesIndexRoute
  '/app/webhooks/': typeof AppWebhooksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/app'
    | '/compare'
    | '/dashboard-tour'
    | '/docs'
    | '/pricing'
    | '/resources'
    | '/setup'
    | '/sign-in'
    | '/sign-up'
    | '/stack'
    | '/use-cases'
    | '/app/analytics'
    | '/app/api-keys'
    | '/app/inbound'
    | '/app/logs'
    | '/app/placement'
    | '/app/preferences'
    | '/app/settings'
    | '/app/suppressions'
    | '/app/team'
    | '/legal/dpa'
    | '/legal/privacy'
    | '/legal/terms'
    | '/app/'
    | '/app/audiences/$audienceId'
    | '/app/automations/$automationId'
    | '/app/broadcasts/$broadcastId'
    | '/app/broadcasts/new'
    | '/app/domains/$domainId'
    | '/app/emails/$emailId'
    | '/app/segments/$segmentId'
    | '/app/templates/$templateId'
    | '/app/webhooks/$webhookId'
    | '/app/audiences/'
    | '/app/automations/'
    | '/app/broadcasts/'
    | '/app/domains/'
    | '/app/segments/'
    | '/app/templates/'
    | '/app/webhooks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/compare'
    | '/dashboard-tour'
    | '/docs'
    | '/pricing'
    | '/resources'
    | '/setup'
    | '/sign-in'
    | '/sign-up'
    | '/stack'
    | '/use-cases'
    | '/app/analytics'
    | '/app/api-keys'
    | '/app/inbound'
    | '/app/logs'
    | '/app/placement'
    | '/app/preferences'
    | '/app/settings'
    | '/app/suppressions'
    | '/app/team'
    | '/legal/dpa'
    | '/legal/privacy'
    | '/legal/terms'
    | '/app'
    | '/app/audiences/$audienceId'
    | '/app/automations/$automationId'
    | '/app/broadcasts/$broadcastId'
    | '/app/broadcasts/new'
    | '/app/domains/$domainId'
    | '/app/emails/$emailId'
    | '/app/segments/$segmentId'
    | '/app/templates/$templateId'
    | '/app/webhooks/$webhookId'
    | '/app/audiences'
    | '/app/automations'
    | '/app/broadcasts'
    | '/app/domains'
    | '/app/segments'
    | '/app/templates'
    | '/app/webhooks'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/app'
    | '/compare'
    | '/dashboard-tour'
    | '/docs'
    | '/pricing'
    | '/resources'
    | '/setup'
    | '/sign-in'
    | '/sign-up'
    | '/stack'
    | '/use-cases'
    | '/app/analytics'
    | '/app/api-keys'
    | '/app/inbound'
    | '/app/logs'
    | '/app/placement'
    | '/app/preferences'
    | '/app/settings'
    | '/app/suppressions'
    | '/app/team'
    | '/legal/dpa'
    | '/legal/privacy'
    | '/legal/terms'
    | '/app/'
    | '/app/audiences/$audienceId'
    | '/app/automations/$automationId'
    | '/app/broadcasts/$broadcastId'
    | '/app/broadcasts/new'
    | '/app/domains/$domainId'
    | '/app/emails/$emailId'
    | '/app/segments/$segmentId'
    | '/app/templates/$templateId'
    | '/app/webhooks/$webhookId'
    | '/app/audiences/'
    | '/app/automations/'
    | '/app/broadcasts/'
    | '/app/domains/'
    | '/app/segments/'
    | '/app/templates/'
    | '/app/webhooks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AppRoute: typeof AppRouteWithChildren
  CompareRoute: typeof CompareRoute
  DashboardTourRoute: typeof DashboardTourRoute
  DocsRoute: typeof DocsRoute
  PricingRoute: typeof PricingRoute
  ResourcesRoute: typeof ResourcesRoute
  SetupRoute: typeof SetupRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  StackRoute: typeof StackRoute
  UseCasesRoute: typeof UseCasesRoute
  LegalDpaRoute: typeof LegalDpaRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-tour': {
      id: '/dashboard-tour'
      path: '/dashboard-tour'
      fullPath: '/dashboard-tour'
      preLoaderRoute: typeof DashboardTourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stack': {
      id: '/stack'
      path: '/stack'
      fullPath: '/stack'
      preLoaderRoute: typeof StackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases': {
      id: '/use-cases'
      path: '/use-cases'
      fullPath: '/use-cases'
      preLoaderRoute: typeof UseCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/api-keys': {
      id: '/app/api-keys'
      path: '/api-keys'
      fullPath: '/app/api-keys'
      preLoaderRoute: typeof AppApiKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inbound': {
      id: '/app/inbound'
      path: '/inbound'
      fullPath: '/app/inbound'
      preLoaderRoute: typeof AppInboundRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/logs': {
      id: '/app/logs'
      path: '/logs'
      fullPath: '/app/logs'
      preLoaderRoute: typeof AppLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/placement': {
      id: '/app/placement'
      path: '/placement'
      fullPath: '/app/placement'
      preLoaderRoute: typeof AppPlacementRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/preferences': {
      id: '/app/preferences'
      path: '/preferences'
      fullPath: '/app/preferences'
      preLoaderRoute: typeof AppPreferencesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/suppressions': {
      id: '/app/suppressions'
      path: '/suppressions'
      fullPath: '/app/suppressions'
      preLoaderRoute: typeof AppSuppressionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/team': {
      id: '/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/legal/dpa': {
      id: '/legal/dpa'
      path: '/legal/dpa'
      fullPath: '/legal/dpa'
      preLoaderRoute: typeof LegalDpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/audiences/': {
      id: '/app/audiences/'
      path: '/audiences'
      fullPath: '/app/audiences/'
      preLoaderRoute: typeof AppAudiencesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audiences/$audienceId': {
      id: '/app/audiences/$audienceId'
      path: '/audiences/$audienceId'
      fullPath: '/app/audiences/$audienceId'
      preLoaderRoute: typeof AppAudiencesAudienceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/automations/': {
      id: '/app/automations/'
      path: '/automations'
      fullPath: '/app/automations/'
      preLoaderRoute: typeof AppAutomationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/automations/$automationId': {
      id: '/app/automations/$automationId'
      path: '/automations/$automationId'
      fullPath: '/app/automations/$automationId'
      preLoaderRoute: typeof AppAutomationsAutomationIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/broadcasts/': {
      id: '/app/broadcasts/'
      path: '/broadcasts'
      fullPath: '/app/broadcasts/'
      preLoaderRoute: typeof AppBroadcastsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/broadcasts/$broadcastId': {
      id: '/app/broadcasts/$broadcastId'
      path: '/broadcasts/$broadcastId'
      fullPath: '/app/broadcasts/$broadcastId'
      preLoaderRoute: typeof AppBroadcastsBroadcastIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/broadcasts/new': {
      id: '/app/broadcasts/new'
      path: '/broadcasts/new'
      fullPath: '/app/broadcasts/new'
      preLoaderRoute: typeof AppBroadcastsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/domains/': {
      id: '/app/domains/'
      path: '/domains'
      fullPath: '/app/domains/'
      preLoaderRoute: typeof AppDomainsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/domains/$domainId': {
      id: '/app/domains/$domainId'
      path: '/domains/$domainId'
      fullPath: '/app/domains/$domainId'
      preLoaderRoute: typeof AppDomainsDomainIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/emails/$emailId': {
      id: '/app/emails/$emailId'
      path: '/emails/$emailId'
      fullPath: '/app/emails/$emailId'
      preLoaderRoute: typeof AppEmailsEmailIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/segments/': {
      id: '/app/segments/'
      path: '/segments'
      fullPath: '/app/segments/'
      preLoaderRoute: typeof AppSegmentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/segments/$segmentId': {
      id: '/app/segments/$segmentId'
      path: '/segments/$segmentId'
      fullPath: '/app/segments/$segmentId'
      preLoaderRoute: typeof AppSegmentsSegmentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/templates/': {
      id: '/app/templates/'
      path: '/templates'
      fullPath: '/app/templates/'
      preLoaderRoute: typeof AppTemplatesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/templates/$templateId': {
      id: '/app/templates/$templateId'
      path: '/templates/$templateId'
      fullPath: '/app/templates/$templateId'
      preLoaderRoute: typeof AppTemplatesTemplateIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/webhooks/': {
      id: '/app/webhooks/'
      path: '/webhooks'
      fullPath: '/app/webhooks/'
      preLoaderRoute: typeof AppWebhooksIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/webhooks/$webhookId': {
      id: '/app/webhooks/$webhookId'
      path: '/webhooks/$webhookId'
      fullPath: '/app/webhooks/$webhookId'
      preLoaderRoute: typeof AppWebhooksWebhookIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppApiKeysRoute: typeof AppApiKeysRoute
  AppInboundRoute: typeof AppInboundRoute
  AppLogsRoute: typeof AppLogsRoute
  AppPlacementRoute: typeof AppPlacementRoute
  AppPreferencesRoute: typeof AppPreferencesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSuppressionsRoute: typeof AppSuppressionsRoute
  AppTeamRoute: typeof AppTeamRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAudiencesAudienceIdRoute: typeof AppAudiencesAudienceIdRoute
  AppAutomationsAutomationIdRoute: typeof AppAutomationsAutomationIdRoute
  AppBroadcastsBroadcastIdRoute: typeof AppBroadcastsBroadcastIdRoute
  AppBroadcastsNewRoute: typeof AppBroadcastsNewRoute
  AppDomainsDomainIdRoute: typeof AppDomainsDomainIdRoute
  AppEmailsEmailIdRoute: typeof AppEmailsEmailIdRoute
  AppSegmentsSegmentIdRoute: typeof AppSegmentsSegmentIdRoute
  AppTemplatesTemplateIdRoute: typeof AppTemplatesTemplateIdRoute
  AppWebhooksWebhookIdRoute: typeof AppWebhooksWebhookIdRoute
  AppAudiencesIndexRoute: typeof AppAudiencesIndexRoute
  AppAutomationsIndexRoute: typeof AppAutomationsIndexRoute
  AppBroadcastsIndexRoute: typeof AppBroadcastsIndexRoute
  AppDomainsIndexRoute: typeof AppDomainsIndexRoute
  AppSegmentsIndexRoute: typeof AppSegmentsIndexRoute
  AppTemplatesIndexRoute: typeof AppTemplatesIndexRoute
  AppWebhooksIndexRoute: typeof AppWebhooksIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppApiKeysRoute: AppApiKeysRoute,
  AppInboundRoute: AppInboundRoute,
  AppLogsRoute: AppLogsRoute,
  AppPlacementRoute: AppPlacementRoute,
  AppPreferencesRoute: AppPreferencesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSuppressionsRoute: AppSuppressionsRoute,
  AppTeamRoute: AppTeamRoute,
  AppIndexRoute: AppIndexRoute,
  AppAudiencesAudienceIdRoute: AppAudiencesAudienceIdRoute,
  AppAutomationsAutomationIdRoute: AppAutomationsAutomationIdRoute,
  AppBroadcastsBroadcastIdRoute: AppBroadcastsBroadcastIdRoute,
  AppBroadcastsNewRoute: AppBroadcastsNewRoute,
  AppDomainsDomainIdRoute: AppDomainsDomainIdRoute,
  AppEmailsEmailIdRoute: AppEmailsEmailIdRoute,
  AppSegmentsSegmentIdRoute: AppSegmentsSegmentIdRoute,
  AppTemplatesTemplateIdRoute: AppTemplatesTemplateIdRoute,
  AppWebhooksWebhookIdRoute: AppWebhooksWebhookIdRoute,
  AppAudiencesIndexRoute: AppAudiencesIndexRoute,
  AppAutomationsIndexRoute: AppAutomationsIndexRoute,
  AppBroadcastsIndexRoute: AppBroadcastsIndexRoute,
  AppDomainsIndexRoute: AppDomainsIndexRoute,
  AppSegmentsIndexRoute: AppSegmentsIndexRoute,
  AppTemplatesIndexRoute: AppTemplatesIndexRoute,
  AppWebhooksIndexRoute: AppWebhooksIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AppRoute: AppRouteWithChildren,
  CompareRoute: CompareRoute,
  DashboardTourRoute: DashboardTourRoute,
  DocsRoute: DocsRoute,
  PricingRoute: PricingRoute,
  ResourcesRoute: ResourcesRoute,
  SetupRoute: SetupRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  StackRoute: StackRoute,
  UseCasesRoute: UseCasesRoute,
  LegalDpaRoute: LegalDpaRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
